remote_theme: oinam/oinam-jekyll
author: polekstulod
title: testing 🔬💻🫶
layout:
  theme: vintage
navbar-links:
  About: 'about'
  Blogs: 'blogs'
  Author's home: 'https://jamespaultulod.tech/'
